version: '3'
services:
  secure.42crunch.test:
    image: 42crunch/apifirewall:latest
    ports:
      - '4241:443'
      - '8880:8880'
    volumes:
      - ./storage/apifirewall/ssl:/opt/guardian/conf/ssl
      - ./storage/apifirewall/logs:/opt/guardian/logs
    command: ["/bin/squire", "-platform", "protection.42crunch.com:8001", "-debug"]
    environment:
      - PROTECTION_TOKEN=${PROTECTION_TOKEN}
      - LISTEN_PORT=443
      - TARGET_URL=https://api-sandbox.ee.co.uk
      - LISTEN_SSL_CERT=full-cert-chain.pem
      - LISTEN_SSL_KEY=key.pem
      - SERVER_NAME=pixi-secured.42crunch.test:4241
      - GUARDIAN_NODE_NAME=BT-API-Firewall
      - GUARDIAN_INSTANCE_NAME=Local-Firewall
      - LOG_LEVEL=DEBUG
      - LOG_DESTINATION=PLATFORM+STDOUT
      - BACKEND_TLS_CHECK_PEER_NAME=off
      - BACKEND_TLS_CHECK_PEER_EXPIRE=off
